//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberLogin
    {
        public long MemberId { get; set; }
        public long LoginProvider { get; set; }
        public long ProviderKey { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
