//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberClaim
    {
        public long Id { get; set; }
        public long MemberId { get; set; }
        public string ClaimType { get; set; }
        public string ClaimValue { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
